name: Oscar Rodríguez Rocha
description: Research Engineer
description2: Ph.D. in Computer and Control Engineering
meta_description: 'Personal website of Oscar Rodríguez Rocha'

aboutPage: false

markdown: kramdown
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://oscarrodriguez.me'
google_analytics: ''
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://oscarrodriguez.me'
author:         'Oscar Rodríguez Rocha'
authorTwitter:  'oscarrodriguez'

exclude: ['LICENSE', 'Rakefile']

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

plugins:
  - jekyll/scholar
  - jekyll-paginate

scholar:
  # style: assets/bibliography/ieee-with-url.csl
  style: apa
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  replace_strings: true

  group_by: type, year
  group_order: descending

  bibliography: ORR_dblp
  bibliography_template: bibliography

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
