name: Oscar Rodríguez Rocha
description: I'm a researcher interested in the Semantic Web, Linked Data, Knowledge Representation, eEducation and Context-Aware Mobile Computing
meta_description: "This is my personal Site, I'm a researcher interested in the Semantic Web, Linked Data, Knowledge Representation, eEducation and Context-Aware Mobile Computing"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://oscarrodriguez.me'
google_analytics: ''
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://oscarrodriguez.me'
author:         'Oscar Rodríguez Rocha'
authorTwitter:  'oscarrodriguez'

exclude: ['LICENSE', 'Rakefile']

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

gems: ['jekyll/scholar']

scholar:
  style: assets/bibliography/ieee-with-url.csl
  locale: 

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  replace_strings: true

  group_by: type, year
  group_order: ascending

  bibliography: ORR_dblp_092016
  bibliography_template: bibliography

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details